<?php

/**
 * @file
 * Install file for the custom_breadcrumbs module.
 */

/**
 * Implements hook_schema().
 */
function custom_breadcrumbs_schema() {
  $schema['custom_breadcrumb'] = array(
    'description' => 'Stores custom breadcrumb trail overrides.',
    'fields' => array(
      'bid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Unique identifier for the {custom_breadcrumb}.',
      ),
      'name' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => FALSE,
        'description' => 'An optional name for the custom breadcrumb.',
      ),
      'titles' => array(
        'type' => 'text',
        'size' => 'medium',
        'not null' => TRUE,
        'description' => 'A return-delimited list of titles for the breadcrumb links.',
      ),
      'paths' => array(
        'type' => 'text',
        'size' => 'medium',
        'not null' => TRUE,
        'description' => 'A return-delimited list of url paths for the breadcrumb links.',
      ),
      'node_type' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => FALSE,
        'default' => 'AND',
        'description' => 'Node types the {custom_breadcrumb} should apply to.',
      ),
      'langcode' => array(
        'type' => 'varchar',
        'length' => 12,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The language this breadcrumb is for; if blank, the breadcrumb will be used for unknown languages.',
      ),
    ),
    'indexes' => array(
      'langcode' => array('langcode'),
      'node_langcode' => array('node_type', 'langcode'),
    ),
    'primary key' => array('bid'),
  );
  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function custom_breadcrumbs_update_last_removed() {
  return 7001;
}

/**
 * @defgroup updates-7.x-to-1.x Updates from 7.x to 1.x
 * @{
 * Update functions from Drupal 7.x to Backdrop CMS 1.x.
 */

/**
 * Move custom breadcrumbs settings from variables to config. Rename language
 * column to langcode and update indexes.
 */
function custom_breadcrumbs_update_1000() {
  // Migrate variables to config.
  $config = config('custom_breadcrumbs.settings');
  $config->set('custom_breadcrumb_home', update_variable_get('custom_breadcrumb_home', 'Home'));
  $config->set('custom_breadcrumb_home_link', update_variable_get('custom_breadcrumb_home_link', '<front>'));
  $config->set('custom_breadcrumbs_append_page_title', update_variable_get('custom_breadcrumbs_append_page_title', FALSE));
  $config->set('custom_breadcrumbs_append_page_title_no_link', update_variable_get('custom_breadcrumbs_append_page_title_no_link', FALSE));
  $config->set('custom_breadcrumbs_set_menu_breadcrumb', update_variable_get('custom_breadcrumbs_set_menu_breadcrumb', FALSE));
  $config->set('custom_breadcrumbs_menu_list', update_variable_get('custom_breadcrumbs_menu_list', array()));
  $config->set('custom_breadcrumbs_set_global_home_breadcrumb', update_variable_get('custom_breadcrumbs_set_global_home_breadcrumb', FALSE));
  $config->set('custom_breadcrumbs_force_active_trail', update_variable_get('custom_breadcrumbs_force_active_trail', FALSE));
  $config->set('custom_breadcrumbs_use_exclude_list', update_variable_get('custom_breadcrumbs_use_exclude_list', FALSE));
  $config->set('custom_breadcrumbs_exclude_list', update_variable_get('custom_breadcrumbs_exclude_list', ""));
  $config->set('custom_breadcrumbs_home_id', update_variable_get('custom_breadcrumbs_home_id', FALSE));
  $config->set('custom_breadcrumbs_home_class', update_variable_get('custom_breadcrumbs_home_class', FALSE));
  $config->set('custom_breadcrumbs_parts_class', update_variable_get('custom_breadcrumbs_parts_class', FALSE));
  $config->set('custom_breadcrumbs_even_odd_class', update_variable_get('custom_breadcrumbs_even_odd_class', FALSE));
  $config->set('custom_breadcrumbs_type_class', update_variable_get('custom_breadcrumbs_type_class', FALSE));
  $config->set('custom_breadcrumbs_append_bid_class', update_variable_get('custom_breadcrumbs_append_bid_class', FALSE));
  $config->save();

  // Delete variables.
  update_variable_del('custom_breadcrumb_home');
  update_variable_del('custom_breadcrumb_home_link');
  update_variable_del('custom_breadcrumbs_append_page_title');
  update_variable_del('custom_breadcrumbs_append_page_title_no_link');
  update_variable_del('custom_breadcrumbs_set_menu_breadcrumb');
  update_variable_del('custom_breadcrumbs_menu_list');
  update_variable_del('custom_breadcrumbs_set_global_home_breadcrumb');
  update_variable_del('custom_breadcrumbs_use_php_in_titles');
  update_variable_del('custom_breadcrumbs_force_active_trail');
  update_variable_del('custom_breadcrumbs_use_exclude_list');
  update_variable_del('custom_breadcrumbs_exclude_list');
  update_variable_del('custom_breadcrumbs_home_id');
  update_variable_del('custom_breadcrumbs_home_class');
  update_variable_del('custom_breadcrumbs_parts_class');
  update_variable_del('custom_breadcrumbs_even_odd_class');
  update_variable_del('custom_breadcrumbs_type_class');
  update_variable_del('custom_breadcrumbs_append_bid_class');
  update_variable_del('custom_breadcrumbs_sort');

  // Rename language column to langcode.
  $langcode_spec = array(
    'type' => 'varchar',
    'length' => 12,
    'not null' => TRUE,
    'default' => '',
    'description' => 'The language this breadcrumb is for; if blank, the breadcrumb will be used for unknown languages.',
  );
  $indexes_spec = array(
    'langcode' => array('langcode'),
    'node_langcode' => array('node_type', 'langcode'),
  );
  db_drop_index('custom_breadcrumb', 'language');
  db_drop_index('custom_breadcrumb', 'node_language');
  db_change_field('custom_breadcrumb', 'language', 'langcode', $langcode_spec, $indexes_spec);

}

/**
 * @} End of "defgroup updates-7.x-to-1.x"
 * The next series of updates should start at 2000.
 */

 /**
  * Remove unneeded PHP visibility field.
  */
function custom_breadcrumbs_update_2000 () {
  if (db_field_exists('custom_breadcrumb', 'visibility_php')) {
    db_drop_field('custom_breadcrumb', 'visibility_php');
  }
}
