<?php

/**
 * @file
 * Install file for the custom_breadcrumbs module.
 */

/**
 * Implements hook_install().
 */
function custom_breadcrumbs_paths_install() {

  $t = get_t();

  // Search for Paths breadcrumbs in existing {custom_breadcrumb} and copy to
  // new table.
  backdrop_set_message($t('Looking for Specify Path breadcrumbs to copy from {custom_breadcrumb}...'));
  $result = db_query("SELECT * FROM {custom_breadcrumb} WHERE node_type = :node_type", array(':node_type' => 'Specify Path'));
  $found = 0;
  foreach ($result as $breadcrumb) {
    $start = strpos($breadcrumb->paths, "\n");
    $specific_path = backdrop_substr($breadcrumb->paths, 0, $start);
    $title = backdrop_substr($breadcrumb->titles, strpos($breadcrumb->titles, "\n") + 1);
    $newpath = backdrop_substr($breadcrumb->paths, strpos($breadcrumb->paths, "\n") + 1);
    db_insert('custom_breadcrumbs_paths')
      ->fields(array(
        'titles' => $title,
        'paths' => $newpath,
        'specific_path' => $specific_path,
        'set_active_menu' => $breadcrumb->set_active_menu,
        'langcode' => $breadcrumb->langcode,
      ))
      ->execute();
    backdrop_set_message($t('Copied path @specific_path to {custom_breadcrumbs_paths}.', array('@specific_path' => $specific_path)));
    ++$found;
  }
  if ($found > 0) {
    backdrop_set_message(format_plural($found, 'Copied 1 breadcrumb.', 'Copied @count breadcrumbs.'));
    backdrop_set_message($t('You can now delete the old Specify Path breadcrumb from <a href="@link">admin/structure/custom_breadcrumbs</a>. They will be listed with title Specify Path and page type node.', array('@link' => url('admin/structure/custom_breadcrumbs'))));
  }
  else {
    backdrop_set_message($t('No Specify Path breadcrumbs were found in {custom_breadcrumb}'));
  }
}

/**
 * Implements hook_schema().
 */
function custom_breadcrumbs_paths_schema() {
  $schema['custom_breadcrumbs_paths'] = array(
    'description' => 'Stores custom breadcrumb trails for specific paths.',
    'fields' => array(
      'bid' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => 'Unique identifier for the {custom_breadcrumbs_views}.',
      ),
      'name' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => FALSE,
        'description' => 'An optional name for the custom breadcrumb.',
      ),
      'titles' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
        'description' => 'A return-delimited list of titles for the breadcrumb links.',
      ),
      'paths' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'description' => 'A return-delimited list of url paths for the breadcrumb links.',
      ),
      'specific_path' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'description' => 'Path to the view for this custom breadcrumb.',
      ),
      'langcode' => array(
        'type' => 'varchar',
        'length' => 12,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The language this breadcrumb is for; if blank, the breadcrumb will be used for unknown languages.',
      ),
    ),
    'indexes' => array(
      'langcode' => array('langcode'),
      'path_langcode' => array('specific_path', 'langcode'),
    ),
    'primary key' => array('bid'),
  );
  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function custom_breadcrumbs_paths_uninstall() {
  // Reset config to defaults.
  config_set('custom_breadcrumbs.settings', 'custom_breadcrumbs_paths_allow_wildcards', FALSE);
}

/**
 * @defgroup updates-7.x-to-1.x Updates from 7.x to 1.x
 * @{
 * Update functions from Drupal 7.x to Backdrop CMS 1.x.
 */

/**
 * Move custom breadcrumbs settings from variables to config. Rename language
 * column to langcode and update indexes.
 */
function custom_breadcrumbs_paths_update_1000() {
  // Migrate variables to config.
  $config = config('custom_breadcrumbs.settings');
  $config->set('custom_breadcrumbs_paths_allow_wildcards', update_variable_get('custom_breadcrumbs_paths_allow_wildcards', FALSE));
  $config->save();

  // Delete variables.
  update_variable_del('custom_breadcrumbs_paths_allow_wildcards');

  // Rename language column to langcode.
  db_drop_index('custom_breadcrumbs_paths', 'language');
  db_drop_index('custom_breadcrumbs_paths', 'path_language');
  $langcode_spec = array(
    'type' => 'varchar',
    'length' => 12,
    'not null' => TRUE,
    'default' => '',
    'description' => 'The language this breadcrumb is for; if blank, the breadcrumb will be used for unknown languages.',
  );
  $indexes_spec = array(
    'langcode' => array('langcode'),
    'path_langcode' => array('specific_path', 'langcode'),
  );
  db_change_field('custom_breadcrumbs_paths', 'language', 'langcode', $langcode_spec, $indexes_spec);
}

/**
 * @} End of "defgroup updates-7.x-to-1.x"
 * The next series of updates should start at 2000.
 */

  /**
  * Remove unneeded PHP visibility field.
  */
  function custom_breadcrumbs_paths_update_2000 () {
    if (db_field_exists('custom_breadcrumbs_paths', 'visibility_php')) {
      db_drop_field('custom_breadcrumbs_paths', 'visibility_php');
    }
  }
